thing = "HELLO world HERE is SOME text"
print(thing.lower())
print(thing.upper())
print(thing.isdligit())
locworld = thing.find("world")
print(locworld)
print(thing[::-1])
print("Is palidrome?", thing == thing[::-1])
print(thing.split(' '))
print("Hello" * 5)